

export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE="CREATE_ORDER_FAILURE";

export const GET_USERS_ORDERS_REQUEST="GET_USERS_ORDERS_REQUEST";
export const GET_USERS_ORDERS_SUCCESS="GET_USERS_ORDERS_SUCCESS";
export const GET_USERS_ORDERS_FAILURE="GET_USERS_ORDERS_FAILURE";

export const GET_RESTAURANT_ORDERS_REQUEST="GET_RESTAURANT_ORDERS_REQUEST";
export const GET_RESTAURANT_ORDERS_SUCCESS="GET_RESTAURANT_ORDERS_SUCCESS";
export const GET_RESTAURANT_ORDERS_FAILURE="GET_RESTAURANT_ORDERS_FAILURE";

export const UPDATE_RESTAURANT_ORDER_REQUEST="UPDATE_RESTAURANT_ORDER_REQUEST";
export const UPDATE_RESTAURANT_ORDER_SUCCESS="UPDATE_RESTAURANT_ORDER_SUCCESS";
export const UPDATE_RESTAURANT_ORDER_FAILURE="UPDATE_RESTAURANT_ORDER_FAILURE";
