
export const GET_INGREDIENTS_REQUEST="GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS="GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILURE="GET_INGREDIENTS_FAILURE";
export const UPDATE_STOCK="UPDATE_STOCK";

export const CREATE_INGREDIENT_REQUEST="CREATE_INGREDIENT_REQUEST";
export const CREATE_INGREDIENT_SUCCESS="CREATE_INGREDIENT_SUCCESS";
export const CREATE_INGREDIENT_FAILURE="CREATE_INGREDIENT_FAILURE";

export const CREATE_INGRREDIENT_CATEGORY_REQUEST="CREATE_INGRREDIENT_CATEGORY_REQUEST";
export const CREATE_INGRREDIENT_CATEGORY_SUCCESS="CREATE_INGRREDIENT_CATEGORY_SUCCESS";
export const CREATE_INGRREDIENT_CATEGORY_FAILURE="CREATE_INGRREDIENT_CATEGORY_FAILURE";

export const GET_INGRREDIENT_CATEGORY_REQUEST="GET_INGRREDIENT_CATEGORY_REQUEST";
export const GET_INGRREDIENT_CATEGORY_SUCCESS="GET_INGRREDIENT_CATEGORY_SUCCESS";
export const GET_INGRREDIENT_CATEGORY_FAILURE="GET_INGRREDIENT_CATEGORY_FAILURE";

export const UPDATE_INGREDIENT_REQUEST="UPDATE_INGREDIENT_REQUEST";
export const UPDATE_INGREDIENT_SUCCESS="UPDATE_INGREDIENT_SUCCESS";
export const UPDATE_INGREDIENT_FAILURE="UPDATE_INGREDIENT_FAILURE";

export const DELETE_INGREDIENT_REQUEST="DELETE_INGREDIENT_REQUEST";
export const DELETE_INGREDIENT_SUCCESS="DELETE_INGREDIENT_SUCCESS";
export const DELETE_INGREDIENT_FAILURE="DELETE_INGREDIENT_FAILURE";
